spring:
  data:
    cassandra:
      local-datacenter: datacenter1
      keyspace-name: userstore
      contact-points: 127.0.0.1
      port: 9042
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      printer:
        enabled: true
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
